runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /api/.*
  script: server.api.app

- url: /mail/send-reminders
  script: server.mail.app
  login: admin

- url: /mail/receive
  script: server.mail.app

- url: /favicon\.ico
  static_files: client/build/favicon.ico
  upload: client/build/favicon\.ico

- url: /asset-manifest\.json
  static_files: client/build/asset-manifest.json
  upload: client/build/asset-manifest\.json

- url: /static
  static_dir: client/build/static

- url: /.*
  static_files: client/build/index.html
  upload: client/build/index\.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/node_modules/.*$
- ^client/public/.*$
- ^client/src/.*$
- ^client/package\.json
- ^client/README\.md
- ^env$  # Python virtual environment folder.